# general settings
name: IconVSR_VOX_Sharp_BI_nf15b8_x4
model_type: IconVSRModel
scale: 4
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: VOX
    type: Vimeo90KDataset
    dataroot_gt: /data2/wei/vox-unalign/GT
    dataroot_lq: /data2/wei/vox-unalign/LR
    meta_info_file: basicsr/data/meta_info/unalign_vox_train.txt
    val_partition: Vimeo90KDateset  # set to 'official' when use the official validation partition
    io_backend:
      type: disk

    is_train: true
    num_frame: 7
    gt_size: 96
    interval_list: [1]
    random_reverse: false
    use_flip: true
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    # pin_memory: true

  val:
    name: VOX
    type: VideoTestVimeo90KDataset
    dataroot_gt: /data2/wei/vox-unalign/GT
    dataroot_lq: /data2/wei/vox-unalign/LR
    meta_info_file: basicsr/data/meta_info/unalign_vox_test.txt
    # val_partition: REDS4  # set to 'official' when use the official validation partition
    io_backend:
      type: disk

    cache_data: false
    num_frame: 7
    padding: reflection_circle


# network structures
network_g:
  type: BasicVSR
  num_feat: 64
  num_block: 30
  spynet_path: pretrained_models/network-sintel-final.pytorch

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    # periods: [250000, 250000, 250000, 250000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up
  fix_iter: 5000
  spynet_lr_mul: 0.125
  edvr_lr_mul: 0.5

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 4e4
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 4e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
